"""added column public id in products

Revision ID: 25c5252be9e4
Revises: 447d6942d464
Create Date: 2026-07-27 18:32:59.201964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c5252be9e4'
down_revision: Union[str, Sequence[str], None] = '447d6942d464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_public_id', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('image_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_public_id')
    op.drop_column('brands', 'image_public_id')
    # ### end Alembic commands ###
