"""fixed delivery address,order,cart

Revision ID: 5afc6362f247
Revises: a5e69341e62d
Create Date: 2026-07-23 10:35:15.088245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5afc6362f247"
down_revision: Union[str, Sequence[str], None] = "a5e69341e62d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Create PostgreSQL enum type before using it
    address_type_enum = sa.Enum(
        "HOME",
        "WORK",
        "HOSTEL",
        "OTHER",
        name="address_type_enum",
    )
    address_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )

    op.add_column(
        "delivery_address",
        sa.Column("reciever_name", sa.String(), nullable=False),
    )
    op.add_column(
        "delivery_address",
        sa.Column("mobile_no", sa.Integer(), nullable=False),
    )
    op.add_column(
        "delivery_address",
        sa.Column("pincode", sa.Integer(), nullable=False),
    )
    op.add_column(
        "delivery_address",
        sa.Column("city", sa.String(), nullable=False),
    )
    op.add_column(
        "delivery_address",
        sa.Column("state", sa.String(), nullable=False),
    )
    op.add_column(
        "delivery_address",
        sa.Column("is_default", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "delivery_address",
        sa.Column("address_type", address_type_enum, nullable=False),
    )
    op.add_column(
        "delivery_address",
        sa.Column("custom_address_type", sa.String(), nullable=True),
    )
    op.add_column(
        "delivery_address",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )

    op.create_index(
        "ix_one_default_address",
        "delivery_address",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default = true"),
    )

    op.create_unique_constraint(
        "uq_user_address",
        "delivery_address",
        ["user_id", "address", "pincode", "state", "city"],
    )

    op.add_column(
        "order_items",
        sa.Column("quantity", sa.Integer(), nullable=False),
    )
    op.add_column(
        "order_items",
        sa.Column("unit_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
    )
    op.add_column(
        "order_items",
        sa.Column("total_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
    )

    op.drop_column("order_items", "quantitiy")
    op.drop_column("order_items", "bought_price")

    op.add_column(
        "orders",
        sa.Column("total_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("address", sa.String(), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("reciever_name", sa.String(), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("mobile_no", sa.Integer(), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("pincode", sa.Integer(), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("city", sa.String(), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("state", sa.String(), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("address_type", address_type_enum, nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("custom_address_type", sa.String(), nullable=True),
    )

    op.drop_column("orders", "total_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "total_price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_column("orders", "custom_address_type")
    op.drop_column("orders", "address_type")
    op.drop_column("orders", "state")
    op.drop_column("orders", "city")
    op.drop_column("orders", "pincode")
    op.drop_column("orders", "mobile_no")
    op.drop_column("orders", "reciever_name")
    op.drop_column("orders", "address")
    op.drop_column("orders", "total_amount")

    op.add_column(
        "order_items",
        sa.Column(
            "bought_price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "order_items",
        sa.Column(
            "quantitiy",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_column("order_items", "total_price")
    op.drop_column("order_items", "unit_price")
    op.drop_column("order_items", "quantity")

    op.drop_constraint("uq_user_address", "delivery_address", type_="unique")
    op.drop_index(
        "ix_one_default_address",
        table_name="delivery_address",
        postgresql_where=sa.text("is_default = true"),
    )

    op.drop_column("delivery_address", "created_at")
    op.drop_column("delivery_address", "custom_address_type")
    op.drop_column("delivery_address", "address_type")
    op.drop_column("delivery_address", "is_default")
    op.drop_column("delivery_address", "state")
    op.drop_column("delivery_address", "city")
    op.drop_column("delivery_address", "pincode")
    op.drop_column("delivery_address", "mobile_no")
    op.drop_column("delivery_address", "reciever_name")

    op.drop_column("cart_items", "created_at")

    # Drop PostgreSQL enum type after all dependent columns are removed
    address_type_enum = sa.Enum(
        "HOME",
        "WORK",
        "HOSTEL",
        "OTHER",
        name="address_type_enum",
    )
    address_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###