"""added subcategory, brand

Revision ID: c7bb27dcb799
Revises: c2eb5386abf6
Create Date: 2026-07-16 16:31:30.162350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bb27dcb799'
down_revision: Union[str, Sequence[str], None] = 'c2eb5386abf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('product_variant', 'variant_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('products', sa.Column('brand_id', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('sub_category_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'products', 'subcategory', ['sub_category_id'], ['id'])
    op.drop_column('products', 'company')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'category', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('products', 'sub_category_id')
    op.drop_column('products', 'brand_id')
    op.alter_column('product_variant', 'variant_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('category', 'is_active')
    op.drop_table('subcategory')
    op.drop_table('brands')
    # ### end Alembic commands ###
