"""fixed the model for dynamic prdouct fetching

Revision ID: f905e2b02f66
Revises: 25c5252be9e4
Create Date: 2026-07-30 10:17:34.818982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f905e2b02f66'
down_revision: Union[str, Sequence[str], None] = '25c5252be9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('main_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('group_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'tag_id', name='uq_section_tag')
    )
    op.create_table('product_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'tag_id', name='uq_product_tag')
    )
    op.drop_table('collection_subcategories')
    op.add_column('category', sa.Column('main_category_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'category', 'main_categories', ['main_category_id'], ['id'])
    op.alter_column('products', 'sub_category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sub_category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'main_category_id')
    op.create_table('collection_subcategories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('collection_subcategories_collection_id_fkey')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], name=op.f('collection_subcategories_subcategory_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_subcategories_pkey'))
    )
    op.drop_table('product_tags')
    op.drop_table('section_tags')
    op.drop_table('sections')
    op.drop_table('main_categories')
    op.drop_table('tags')
    # ### end Alembic commands ###
