import time
import uuid

from fastapi import Request
from app.core.logger import logger


async def logging_middleware(request: Request, call_next):

    # Generate a unique ID for this request.
    # It helps developers trace one request across logs.
    request_id = str(uuid.uuid4())

    # Store request start time so we can calculate response time.
    start_time = time.perf_counter()

    # Log when the request enters the application.
    logger.info(
        "Request received | "
        "request_id=%s | "
        "method=%s | "
        "path=%s | "
        "client=%s",
        request_id,
        request.method,
        request.url.path,
        request.client.host if request.client else "unknown",
    )

    try:
        # Pass the request to the actual FastAPI endpoint.
        response = await call_next(request)

        # Calculate how long the request took.
        process_time = time.perf_counter() - start_time

        # Log the response generated by the endpoint.
        logger.info(
            "Request completed | "
            "request_id=%s | "
            "method=%s | "
            "path=%s | "
            "status_code=%s | "
            "client=%s | "
            "duration=%.4fs",
            request_id,
            request.method,
            request.url.path,
            response.status_code,
            request.client.host if request.client else "unknown",
            process_time,
        )

        # Add request ID to response so the client can also trace it.
        response.headers["X-Request-ID"] = request_id

        return response

    except Exception:
        # Calculate duration even when an unexpected error occurs.
        process_time = time.perf_counter() - start_time

        # logger.exception automatically includes the traceback.
        logger.exception(
            "Request failed | "
            "request_id=%s | "
            "method=%s | "
            "path=%s | "
            "client=%s | "
            "duration=%.4fs",
            request_id,
            request.method,
            request.url.path,
            request.client.host if request.client else "unknown",
            process_time,
        )

        # Re-raise the exception so FastAPI can handle it normally.
        raise